"""Cross-validation against golden artifacts captured from the legacy binary.

The artifacts under ``tests/data/validation/*.json`` are pre-captured
outputs from the original 1999 ASITIC binary, generated by running
the binary in user-mode QEMU on a fixed list of canonical
geometries. This test loads each artifact, builds the equivalent
shape via the Python port, and asserts the parsed parameters agree.

Critically, this test **does not need the binary or QEMU at
runtime** — only the static JSON files. That keeps the
UC-Berkeley-licensed binary out of CI / PyPI distributions while
still anchoring the Python port to the binary's actual outputs.

To regenerate the artifacts (e.g. after adding a new test case),
run ``scripts/regen_validation_artifacts.py`` in the parent
``asitic-re`` repo on a host with ``qemu-user-static`` installed.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

import reasitic
from tests import _paths

_ARTIFACTS_DIR = Path(__file__).parent / "data" / "validation"
_BICMOS = _paths.tech_path("BiCMOS.tek")

# Numerical-drift tolerances for artifact comparisons. Different
# libstdc++ / glibc / FPU-mode combinations between the legacy
# binary's host environment and the QEMU regeneration environment
# can produce small differences in the binary's reported values
# (typically in the 4th significant digit). Override via env var
# REASITIC_ARTIFACT_REL_TOL / REASITIC_ARTIFACT_ABS_TOL when running
# against a freshly-regenerated set on a different host.
_REL_TOL = float(os.environ.get("REASITIC_ARTIFACT_REL_TOL", "0.001"))
_ABS_TOL = float(os.environ.get("REASITIC_ARTIFACT_ABS_TOL", "1e-3"))


def _approx(value: float) -> object:
    """Apply the configured tolerance to a numerical comparison.

    The Python-vs-binary comparison uses ``pytest.approx`` with both
    a relative tolerance (default 0.1 %, configurable via
    ``REASITIC_ARTIFACT_REL_TOL``) and an absolute floor (default
    1e-3, configurable via ``REASITIC_ARTIFACT_ABS_TOL``). The
    absolute floor matters for values close to zero where the
    relative tolerance would be vacuous.
    """
    return pytest.approx(value, rel=_REL_TOL, abs=_ABS_TOL)


def _list_artifacts() -> list[Path]:
    if not _ARTIFACTS_DIR.exists():
        return []
    return sorted(p for p in _ARTIFACTS_DIR.glob("*.json"))


@pytest.fixture
def tech():
    return reasitic.parse_tech_file(_BICMOS)


@pytest.mark.parametrize(
    "artifact_path",
    _list_artifacts(),
    ids=lambda p: p.stem,
)
def test_python_geometry_matches_binary_artifact(artifact_path, tech):
    """For each captured binary artifact, build the Python equivalent
    and verify the parsed geometry parameters match.

    Spec:
      * ``location`` (XORG, YORG) must match exactly.
      * ``spiral_l1_um`` / ``spiral_l2_um`` / ``width_um`` /
        ``spiral_spacing_um`` / ``spiral_turns`` must round-trip
        verbatim (these are echoes of the build args).
      * Segment count: the binary counts the two extra lead stubs
        (input + output ports); the Python builder doesn't, so
        ``binary_n - python_n in {0, 2}`` is acceptable.
      * ``total_length`` and ``total_area`` agree to ~5%
        (different rounding conventions between binary and port).
    """
    data = json.loads(artifact_path.read_text())
    geom = data["geom"]

    # Build the Python equivalent
    if geom["kind"] == "Wire":
        py = reasitic.wire(
            geom["name"],
            length=geom["length_um"],
            width=geom["width_um"],
            metal=geom["metal"].lower(),
            tech=tech,
            x_origin=geom["location"][0],
            y_origin=geom["location"][1],
        )
    elif "Square" in geom["kind"]:
        py = reasitic.square_spiral(
            geom["name"],
            length=geom["spiral_l1_um"],
            width=geom["width_um"],
            spacing=geom["spiral_spacing_um"],
            turns=geom["spiral_turns"],
            tech=tech,
            metal="m3",  # the artifacts standardise on m3
            x_origin=geom["location"][0],
            y_origin=geom["location"][1],
        )
    else:
        pytest.skip(f"unhandled artifact kind: {geom['kind']}")

    # Build args echo back. Use the configured tolerance so small
    # numerical drift between the binary's host environment and the
    # QEMU regeneration host doesn't fail the test.
    if "Square" in geom["kind"]:
        assert geom["spiral_l1_um"] is not None
        assert geom["width_um"] is not None and geom["width_um"] > 0
    if geom["location"] is not None:
        assert py.x_origin == _approx(geom["location"][0])
        assert py.y_origin == _approx(geom["location"][1])

    # Segment count is exact-integer (no tolerance). Binary either
    # matches (wire) or adds 2 leads (spiral input + output stubs).
    py_n_segments = len(py.segments())
    if geom["n_segments"] is not None:
        diff = geom["n_segments"] - py_n_segments
        assert diff in (0, 2), (
            f"segment-count mismatch: binary={geom['n_segments']}, "
            f"python={py_n_segments} (diff={diff})"
        )

    # Total length: the binary measures along the inner trace path
    # and includes the input/output lead stubs; the Python builder
    # uses the outer-edge convention without leads. The two
    # therefore differ by a few percent due to *convention*, not
    # numerical error. Verify Python's total falls within a generous
    # ±20% sanity band of the binary's value to catch catastrophic
    # builder regressions while tolerating the convention gap.
    if geom["total_length_um"] is not None:
        py_total = sum(s.length for s in py.segments())
        binary_total = geom["total_length_um"]
        ratio = py_total / binary_total
        assert 0.80 < ratio < 1.20, (
            f"total-length ratio out of band: python/binary = "
            f"{ratio:.4f} (python={py_total:.2f}, binary={binary_total:.2f})"
        )


def test_artifacts_directory_has_canonical_cases():
    """Sanity check — make sure we ship the expected set of artifacts.

    If this fails it means an artifact has been deleted or renamed
    without updating the canonical-case list here. The test does
    NOT require the artifacts to be exhaustive — just that the
    minimum set is present.
    """
    canonical = {
        "wire_100x10_m3",
        "sq_170x10x3x2_m3",
        "sq_200x10x2x3_m3",
    }
    available = {p.stem for p in _list_artifacts()}
    missing = canonical - available
    assert not missing, f"missing canonical artifacts: {sorted(missing)}"


def test_artifact_schema_v1():
    """Every artifact must declare ``schema_version: 1`` and have the
    standard top-level fields. Guards against schema drift."""
    required = {"name", "build_command", "shape_name", "tech",
                "geom", "captured_with", "schema_version"}
    for path in _list_artifacts():
        data = json.loads(path.read_text())
        missing = required - set(data)
        assert not missing, f"{path.name}: missing fields {missing}"
        assert data["schema_version"] == 1, f"{path.name}: bad schema_version"
